// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarTrak.Api.Infrastructure;

namespace StarTrak.Api.Migrations
{
    [DbContext(typeof(MsSqlDbContext))]
    [Migration("20190216211216_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarTrak.Api.Model.GpsData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AltRef");

                    b.Property<string>("EwIndicator");

                    b.Property<string>("Fs");

                    b.Property<DateTime>("GpsUTC");

                    b.Property<string>("Hdop");

                    b.Property<string>("Lon");

                    b.Property<string>("MacAddress");

                    b.Property<string>("Msl");

                    b.Property<string>("Name");

                    b.Property<string>("NoSv");

                    b.Property<string>("NsIndicator");

                    b.Property<string>("Umsl");

                    b.Property<string>("Usep");

                    b.HasKey("Id");

                    b.ToTable("GpsData");
                });
#pragma warning restore 612, 618
        }
    }
}
