// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarTrak.Service.Gps.Persistence;

namespace StarTrak.Service.Gps.Migrations
{
    [DbContext(typeof(GpsDbContext))]
    [Migration("20190309202516_InitialDatabaseCreate")]
    partial class InitialDatabaseCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StarTrak.Service.Gps.Models.GpsData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Altitude");

                    b.Property<float>("EWIndicator");

                    b.Property<string>("FS");

                    b.Property<DateTime>("GpsUtcDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("HDop");

                    b.Property<float>("Latitude");

                    b.Property<float>("Longitude");

                    b.Property<string>("MSL");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("char(20)");

                    b.Property<float>("NSIndicator");

                    b.Property<string>("NoSv");

                    b.Property<Guid>("PlayerId");

                    b.Property<string>("ProtocolHeader")
                        .IsRequired();

                    b.Property<string>("UMsl");

                    b.Property<string>("USep");

                    b.HasKey("Id");

                    b.ToTable("GpsData");
                });
#pragma warning restore 612, 618
        }
    }
}
